version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '3311:3311'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123456